//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbContainer : DbContext
    {
        public DbContainer()
            : base("name=DbContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_SysUser> tbl_SysUser { get; set; }
        public virtual DbSet<tbl_SysUserRole> tbl_SysUserRole { get; set; }
        public virtual DbSet<YZJ_CheckType> YZJ_CheckType { get; set; }
        public virtual DbSet<YZJ_CredentialsType> YZJ_CredentialsType { get; set; }
        public virtual DbSet<YZJ_Info> YZJ_Info { get; set; }
        public virtual DbSet<YZJ_Score> YZJ_Score { get; set; }
        public virtual DbSet<YZJ_StatusType> YZJ_StatusType { get; set; }
        public virtual DbSet<YZJ_StdGraduationRecord> YZJ_StdGraduationRecord { get; set; }
        public virtual DbSet<YZJ_Grade> YZJ_Grade { get; set; }
        public virtual DbSet<YZJ_CheckRecord> YZJ_CheckRecord { get; set; }
        public virtual DbSet<tbl_SysModule> tbl_SysModule { get; set; }
        public virtual DbSet<tbl_SysPermission> tbl_SysPermission { get; set; }
        public virtual DbSet<tbl_SysRole> tbl_SysRole { get; set; }
        public virtual DbSet<YZJ_Status> YZJ_Status { get; set; }
    }
}
