//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SysModule
    {
        public string Id { get; set; }
        public string ModuleId { get; set; }
        public string ModuleName { get; set; }
        public string ParentId { get; set; }
        public string ModuleURL { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<bool> IsLast { get; set; }
    }
}
