//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SysRole
    {
        public string RoleId { get; set; }
        public string RoleName { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<bool> IsShow { get; set; }
    }
}
