//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace SchoolManager.Models
{
	public partial class SysRoleModel : Virtual_SysRoleModel
	{

	}
	public class Virtual_SysRoleModel
	{
		public virtual string RoleId { get; set;}
		public virtual string RoleName { get; set;}
		public virtual Nullable<int> Sort { get; set;}
		public virtual Nullable<bool> IsShow { get; set;}
	}
}
