
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


using System;

namespace SchoolManager.Models
{
	public partial class SysModulePermissionModel : Virtual_SysModulePermissionModel
	{

	}
	public class Virtual_SysModulePermissionModel
	{
		public virtual string Id { get; set;}
		public virtual string ModuleId { get; set;}
		public virtual string PermissionId { get; set;}

	}

}
