
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


using System;

namespace SchoolManager.Models
{
	public partial class YZJ_StdGraduationRecordModel : Virtual_YZJ_StdGraduationRecordModel
	{

	}
	public class Virtual_YZJ_StdGraduationRecordModel
	{
		public virtual int id { get; set;}
		public virtual Nullable<bool> available { get; set;}
		public virtual string StdId { get; set;}
		public virtual string StdName { get; set;}
		public virtual string StdRollId { get; set;}
		public virtual string GraduatedSchoolname { get; set;}
		public virtual string GraduatedSchoolNo { get; set;}

	}

}
