//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace SchoolManager.Models
{
	public partial class YZJ_CheckRecordModel : Virtual_YZJ_CheckRecordModel
	{

	}
	public class Virtual_YZJ_CheckRecordModel
	{
		public virtual string id { get; set;}
		public virtual Nullable<bool> available { get; set;}
		public virtual Nullable<int> StdId { get; set;}
		public virtual string StdName { get; set;}
		public virtual string ApplicantNo { get; set;}
		public virtual string ApplicantName { get; set;}
		public virtual Nullable<System.DateTime> ApplyDate { get; set;}
		public virtual Nullable<int> AssessorId { get; set;}
		public virtual string AssessorName { get; set;}
		public virtual Nullable<System.DateTime> AssessDate { get; set;}
		public virtual Nullable<int> ExaminantId { get; set;}
		public virtual string ExaminantName { get; set;}
		public virtual string ExamineName { get; set;}
		public virtual Nullable<System.DateTime> ExamineDate { get; set;}
		public virtual string AssessResult { get; set;}
		public virtual string AssessState { get; set;}
		public virtual string ApplyReason { get; set;}
		public virtual string ExamineOpinion { get; set;}
		public virtual string ApplyType { get; set;}
	}
}
