//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace SchoolManager.Models
{
	public partial class YZJ_ScoreModel : Virtual_YZJ_ScoreModel
	{

	}
	public class Virtual_YZJ_ScoreModel
	{
		public virtual int id { get; set;}
		public virtual Nullable<bool> available { get; set;}
		public virtual string Grade { get; set;}
		public virtual string ClassNo { get; set;}
	}
}
