
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


using System;

namespace SchoolManager.Models
{
	public partial class wyqstudentModel : Virtual_wyqstudentModel
	{

	}
	public class Virtual_wyqstudentModel
	{
		public virtual string Sno { get; set;}
		public virtual string Sname { get; set;}
		public virtual string Ssex { get; set;}
		public virtual string State { get; set;}
		public virtual string Intime { get; set;}
		public virtual string SSymbol { get; set;}
		public virtual string Classno { get; set;}
		public virtual string Gradeno { get; set;}
		public virtual string Province { get; set;}
		public virtual string SAddress { get; set;}
		public virtual string STel { get; set;}

	}

}
