//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace SchoolManager.Models
{
	public partial class YZJ_StatusModel : Virtual_YZJ_StatusModel
	{

	}
	public class Virtual_YZJ_StatusModel
	{
		public virtual string id { get; set;}
		public virtual Nullable<bool> available { get; set;}
		public virtual string StdRollId { get; set;}
		public virtual string StdName { get; set;}
		public virtual string StdSex { get; set;}
		public virtual string native { get; set;}
		public virtual string nation { get; set;}
		public virtual string Entrance_Year { get; set;}
		public virtual string Household_Registration_Category { get; set;}
		public virtual string HouseholdAddress { get; set;}
		public virtual string CurrentAddress { get; set;}
		public virtual byte[] Photo { get; set;}
		public virtual string PhoneNumber { get; set;}
		public virtual string UrgentPhoneNumber { get; set;}
		public virtual string PaperType { get; set;}
		public virtual string PaperNumber { get; set;}
		public virtual string UsedName { get; set;}
		public virtual string email { get; set;}
		public virtual string PostCode { get; set;}
		public virtual Nullable<int> IsLeagueeMember { get; set;}
		public virtual Nullable<int> IsYoungPineer { get; set;}
		public virtual string GuardianNo1 { get; set;}
		public virtual string G1PhoneNumber { get; set;}
		public virtual string G1Relationship { get; set;}
		public virtual string GuardianNo2 { get; set;}
		public virtual string G2PhoneNumber { get; set;}
		public virtual string G2Relationship { get; set;}
		public virtual string AlmaMater { get; set;}
		public virtual string StdCategory { get; set;}
		public virtual string StatusState { get; set;}
	}
}
