//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace SchoolManager.Models
{
	public partial class YZJ_InfoModel : Virtual_YZJ_InfoModel
	{

	}
	public class Virtual_YZJ_InfoModel
	{
		public virtual string id { get; set;}
		public virtual Nullable<bool> available { get; set;}
		public virtual string StdRollId { get; set;}
		public virtual string StdId { get; set;}
		public virtual string StdName { get; set;}
		public virtual string StdSex { get; set;}
		public virtual string RepeatNo { get; set;}
		public virtual string Entrance_Year { get; set;}
		public virtual string ClassNo { get; set;}
		public virtual Nullable<bool> InResidence { get; set;}
		public virtual string DormitoryBuilding { get; set;}
		public virtual string DormitoryNo { get; set;}
		public virtual string AddProvince { get; set;}
		public virtual string AddCity { get; set;}
		public virtual string AddArea { get; set;}
		public virtual string AddStreet { get; set;}
		public virtual string AddDetail { get; set;}
	}
}
