
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


using System;

namespace SchoolManager.Models
{
	public partial class SysUserModel : Virtual_SysUserModel
	{

	}
	public class Virtual_SysUserModel
	{
		public virtual string UserId { get; set;}
		public virtual string UserName { get; set;}
		public virtual string PassWord { get; set;}
		public virtual string PhoneNumber { get; set;}
		public virtual string SchoolCard { get; set;}
		public virtual string Sex { get; set;}
		public virtual string DepId { get; set;}
		public virtual string PosId { get; set;}

	}

}
