//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace SchoolManager.Models
{
	public partial class SysModuleModel : Virtual_SysModuleModel
	{

	}
	public class Virtual_SysModuleModel
	{
		public virtual string Id { get; set;}
		public virtual string ModuleId { get; set;}
		public virtual string ModuleName { get; set;}
		public virtual string ParentId { get; set;}
		public virtual string ModuleURL { get; set;}
		public virtual Nullable<bool> IsShow { get; set;}
		public virtual Nullable<bool> IsLast { get; set;}
	}
}
