//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wyqstudent
    {
        public string Sno { get; set; }
        public string Sname { get; set; }
        public string Ssex { get; set; }
        public string State { get; set; }
        public string Intime { get; set; }
        public string SSymbol { get; set; }
        public string Classno { get; set; }
        public string Gradeno { get; set; }
        public string Province { get; set; }
        public string SAddress { get; set; }
        public string STel { get; set; }
    }
}
