//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YZJ_Info
    {
        public string id { get; set; }
        public Nullable<bool> available { get; set; }
        public string StdRollId { get; set; }
        public string StdId { get; set; }
        public string StdName { get; set; }
        public string StdSex { get; set; }
        public string RepeatNo { get; set; }
        public string Entrance_Year { get; set; }
        public string ClassNo { get; set; }
        public Nullable<bool> InResidence { get; set; }
        public string DormitoryBuilding { get; set; }
        public string DormitoryNo { get; set; }
        public string AddProvince { get; set; }
        public string AddCity { get; set; }
        public string AddArea { get; set; }
        public string AddStreet { get; set; }
        public string AddDetail { get; set; }
    }
}
