//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YZJ_Status
    {
        public string id { get; set; }
        public Nullable<bool> available { get; set; }
        public string StdRollId { get; set; }
        public string StdName { get; set; }
        public string StdSex { get; set; }
        public string native { get; set; }
        public string nation { get; set; }
        public string Entrance_Year { get; set; }
        public string Household_Registration_Category { get; set; }
        public string HouseholdAddress { get; set; }
        public string CurrentAddress { get; set; }
        public byte[] Photo { get; set; }
        public string PhoneNumber { get; set; }
        public string UrgentPhoneNumber { get; set; }
        public string PaperType { get; set; }
        public string PaperNumber { get; set; }
        public string UsedName { get; set; }
        public string email { get; set; }
        public string PostCode { get; set; }
        public Nullable<int> IsLeagueeMember { get; set; }
        public Nullable<int> IsYoungPineer { get; set; }
        public string GuardianNo1 { get; set; }
        public string G1PhoneNumber { get; set; }
        public string G1Relationship { get; set; }
        public string GuardianNo2 { get; set; }
        public string G2PhoneNumber { get; set; }
        public string G2Relationship { get; set; }
        public string AlmaMater { get; set; }
        public string StdCategory { get; set; }
    }
}
