//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YZJ_CheckRecord
    {
        public string id { get; set; }
        public Nullable<bool> available { get; set; }
        public string StdId { get; set; }
        public string StdName { get; set; }
        public string ApplicantNo { get; set; }
        public string ApplicantName { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
        public Nullable<int> AssessorId { get; set; }
        public string AssessorName { get; set; }
        public Nullable<System.DateTime> AssessDate { get; set; }
        public Nullable<int> ExaminantId { get; set; }
        public string ExaminantName { get; set; }
        public string ExamineName { get; set; }
        public Nullable<System.DateTime> ExamineDate { get; set; }
        public string AssessResult { get; set; }
        public string AssessState { get; set; }
        public string ApplyReason { get; set; }
        public string ExamineOpinion { get; set; }
        public string ApplyType { get; set; }
    }
}
