//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using SchoolManager.Models;
using SchoolManager.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using SchoolManager.DAL;
using SchoolManager.BLL;
using Unity.Attributes;

namespace SchoolManager.BLL
{
	public class Virtual_YZJ_StatusTypeBLL
	{

        public YZJ_StatusTypeRepository m_Rep =new YZJ_StatusTypeRepository(new DbContainer());

		public virtual List<YZJ_StatusTypeModel> GetList( string queryStr)
        {

            IQueryable<YZJ_StatusType> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
								
								a=>(a.Name!=null && a.Name.Contains(queryStr))
								);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            return CreateModelList(ref queryData);
        }

        public virtual List<YZJ_StatusTypeModel> CreateModelList(ref IQueryable<YZJ_StatusType> queryData)
        {

            List<YZJ_StatusTypeModel> modelList = (from r in queryData
                                              select new YZJ_StatusTypeModel
                                              {
													ID = r.ID,
													Name = r.Name,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(YZJ_StatusTypeModel model)
        {
            try
            {
                YZJ_StatusType entity = m_Rep.GetById(model.ID);
                if (entity != null)
                {
                    return false;
                }
                entity = new YZJ_StatusType();
               				entity.ID = model.ID;
				entity.Name = model.Name;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {

                return false;
            }
        }



         public virtual bool Delete( string id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {

                return false;
            }
        }

        public virtual bool Delete( string[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {

                return false;
            }
        }

		
       

        public virtual bool Edit( YZJ_StatusTypeModel model)
        {
            try
            {
                YZJ_StatusType entity = m_Rep.GetById(model.ID);
                if (entity == null)
                {
                    return false;
                }
                              				entity.ID = model.ID;
				entity.Name = model.Name;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    return false;
                }

            }
            catch (Exception ex)
            {                

                return false;
            }
        }

      

        public virtual YZJ_StatusTypeModel GetById(string id)
        {
            if (IsExists(id))
            {
                YZJ_StatusType entity = m_Rep.GetById(id);
                YZJ_StatusTypeModel model = new YZJ_StatusTypeModel();
                              				model.ID = entity.ID;
				model.Name = entity.Name;
 
                return model;
            }
            else
            {
                return null;
            }
        }

        public virtual bool IsExists(string id)
        {
            return m_Rep.IsExist(id);
        }
		  public void Dispose()
        { 
            
        }

	}
}
