
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using SchoolManager.Models;
using SchoolManager.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using SchoolManager.DAL;
using SchoolManager.BLL;
using Unity.Attributes;

namespace SchoolManager.BLL
{
	public class Virtual_YZJ_ScoreBLL
	{

        public YZJ_ScoreRepository m_Rep =new YZJ_ScoreRepository(new DbContainer());

		public virtual List<YZJ_ScoreModel> GetList( string queryStr)
        {

            IQueryable<YZJ_Score> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
								
								
								a=>(a.Grade!=null && a.Grade.Contains(queryStr))
								|| (a.ClassNo!=null && a.ClassNo.Contains(queryStr))
								);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            return CreateModelList(ref queryData);
        }

        public virtual List<YZJ_ScoreModel> CreateModelList(ref IQueryable<YZJ_Score> queryData)
        {

            List<YZJ_ScoreModel> modelList = (from r in queryData
                                              select new YZJ_ScoreModel
                                              {
													id = r.id,
													available = r.available,
													Grade = r.Grade,
													ClassNo = r.ClassNo,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(YZJ_ScoreModel model)
        {
            try
            {
                YZJ_Score entity = m_Rep.GetById(model.id);
                if (entity != null)
                {
                    return false;
                }
                entity = new YZJ_Score();
               				entity.id = model.id;
				entity.available = model.available;
				entity.Grade = model.Grade;
				entity.ClassNo = model.ClassNo;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {

                return false;
            }
        }



         public virtual bool Delete( string id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {

                return false;
            }
        }

        public virtual bool Delete( string[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {

                return false;
            }
        }

		
       

        public virtual bool Edit( YZJ_ScoreModel model)
        {
            try
            {
                YZJ_Score entity = m_Rep.GetById(model.id);
                if (entity == null)
                {
                    return false;
                }
                              				entity.id = model.id;
				entity.available = model.available;
				entity.Grade = model.Grade;
				entity.ClassNo = model.ClassNo;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    return false;
                }

            }
            catch (Exception ex)
            {                

                return false;
            }
        }

      

        public virtual YZJ_ScoreModel GetById(string id)
        {
            if (IsExists(id))
            {
                YZJ_Score entity = m_Rep.GetById(id);
                YZJ_ScoreModel model = new YZJ_ScoreModel();
                              				model.id = entity.id;
				model.available = entity.available;
				model.Grade = entity.Grade;
				model.ClassNo = entity.ClassNo;
 
                return model;
            }
            else
            {
                return null;
            }
        }

        public virtual bool IsExists(string id)
        {
            return m_Rep.IsExist(id);
        }
		  public void Dispose()
        { 
            
        }

	}

}
