//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using SchoolManager.Models;
using SchoolManager.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using SchoolManager.DAL;
using SchoolManager.BLL;
using Unity.Attributes;

namespace SchoolManager.BLL
{
	public class Virtual_SysRolePermissionBLL
	{

        public SysRolePermissionRepository m_Rep =new SysRolePermissionRepository(new DbContainer());

		public virtual List<SysRolePermissionModel> GetList( string queryStr)
        {

            IQueryable<tbl_SysRolePermission> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
								a=>(a.Id!=null && a.Id.Contains(queryStr))
								|| (a.RoleId!=null && a.RoleId.Contains(queryStr))
								|| (a.ModelPermissionId!=null && a.ModelPermissionId.Contains(queryStr))
								);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            return CreateModelList(ref queryData);
        }

        public virtual List<SysRolePermissionModel> CreateModelList(ref IQueryable<tbl_SysRolePermission> queryData)
        {

            List<SysRolePermissionModel> modelList = (from r in queryData
                                              select new SysRolePermissionModel
                                              {
													Id = r.Id,
													RoleId = r.RoleId,
													ModelPermissionId = r.ModelPermissionId,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(ref ValidationErrors errors, SysRolePermissionModel model)
        {
            try
            {
                tbl_SysRolePermission entity = m_Rep.GetById(model.Id);
                if (entity != null)
                {
                    errors.Add(Suggestion.PrimaryRepeat);
                    return false;
                }
                entity = new tbl_SysRolePermission();
               				entity.Id = model.Id;
				entity.RoleId = model.RoleId;
				entity.ModelPermissionId = model.ModelPermissionId;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Suggestion.InsertFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHandler.WriteException(ex);
                return false;
            }
        }



         public virtual bool Delete(ref ValidationErrors errors, string id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHandler.WriteException(ex);
                return false;
            }
        }

        public virtual bool Delete(ref ValidationErrors errors, string[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHandler.WriteException(ex);
                return false;
            }
        }

		
       

        public virtual bool Edit(ref ValidationErrors errors, SysRolePermissionModel model)
        {
            try
            {
                tbl_SysRolePermission entity = m_Rep.GetById(model.Id);
                if (entity == null)
                {
                    errors.Add(Suggestion.Disable);
                    return false;
                }
                              				entity.Id = model.Id;
				entity.RoleId = model.RoleId;
				entity.ModelPermissionId = model.ModelPermissionId;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Suggestion.EditFail);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHandler.WriteException(ex);
                return false;
            }
        }

      

        public virtual SysRolePermissionModel GetById(string id)
        {
            if (IsExists(id))
            {
                tbl_SysRolePermission entity = m_Rep.GetById(id);
                SysRolePermissionModel model = new SysRolePermissionModel();
                              				model.Id = entity.Id;
				model.RoleId = entity.RoleId;
				model.ModelPermissionId = entity.ModelPermissionId;
 
                return model;
            }
            else
            {
                return null;
            }
        }

        public virtual bool IsExists(string id)
        {
            return m_Rep.IsExist(id);
        }
		  public void Dispose()
        { 
            
        }

	}
}
