//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using SchoolManager.Models;
using SchoolManager.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using SchoolManager.DAL;
using SchoolManager.BLL;
using Unity.Attributes;

namespace SchoolManager.BLL
{
	public class Virtual_YZJ_InfoBLL
	{

        public YZJ_InfoRepository m_Rep =new YZJ_InfoRepository(new DbContainer());

		public virtual List<YZJ_InfoModel> GetList( string queryStr)
        {

            IQueryable<YZJ_Info> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
								
								
								a=>(a.StdId!=null && a.StdId.Contains(queryStr))
								|| (a.StdName!=null && a.StdName.Contains(queryStr))
								|| (a.StdSex!=null && a.StdSex.Contains(queryStr))
								|| (a.RepeatNo!=null && a.RepeatNo.Contains(queryStr))
								|| (a.Entrance_Year!=null && a.Entrance_Year.Contains(queryStr))
								|| (a.ClassNo!=null && a.ClassNo.Contains(queryStr))
								
								|| (a.DormitoryBuilding!=null && a.DormitoryBuilding.Contains(queryStr))
								|| (a.DormitoryNo!=null && a.DormitoryNo.Contains(queryStr))
								|| (a.AddProvince!=null && a.AddProvince.Contains(queryStr))
								|| (a.AddCity!=null && a.AddCity.Contains(queryStr))
								|| (a.AddArea!=null && a.AddArea.Contains(queryStr))
								|| (a.AddStreet!=null && a.AddStreet.Contains(queryStr))
								|| (a.AddDetail!=null && a.AddDetail.Contains(queryStr))
								);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            return CreateModelList(ref queryData);
        }

        public virtual List<YZJ_InfoModel> CreateModelList(ref IQueryable<YZJ_Info> queryData)
        {

            List<YZJ_InfoModel> modelList = (from r in queryData
                                              select new YZJ_InfoModel
                                              {
													id = r.id,
													available = r.available,
													StdId = r.StdId,
													StdName = r.StdName,
													StdSex = r.StdSex,
													RepeatNo = r.RepeatNo,
													Entrance_Year = r.Entrance_Year,
													ClassNo = r.ClassNo,
													InResidence = r.InResidence,
													DormitoryBuilding = r.DormitoryBuilding,
													DormitoryNo = r.DormitoryNo,
													AddProvince = r.AddProvince,
													AddCity = r.AddCity,
													AddArea = r.AddArea,
													AddStreet = r.AddStreet,
													AddDetail = r.AddDetail,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(YZJ_InfoModel model)
        {
            try
            {
                YZJ_Info entity = m_Rep.GetById(model.id);
                if (entity != null)
                {
                    return false;
                }
                entity = new YZJ_Info();
               				entity.id = model.id;
				entity.available = model.available;
				entity.StdId = model.StdId;
				entity.StdName = model.StdName;
				entity.StdSex = model.StdSex;
				entity.RepeatNo = model.RepeatNo;
				entity.Entrance_Year = model.Entrance_Year;
				entity.ClassNo = model.ClassNo;
				entity.InResidence = model.InResidence;
				entity.DormitoryBuilding = model.DormitoryBuilding;
				entity.DormitoryNo = model.DormitoryNo;
				entity.AddProvince = model.AddProvince;
				entity.AddCity = model.AddCity;
				entity.AddArea = model.AddArea;
				entity.AddStreet = model.AddStreet;
				entity.AddDetail = model.AddDetail;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {

                return false;
            }
        }



         public virtual bool Delete( string id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {

                return false;
            }
        }

        public virtual bool Delete( string[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {

                return false;
            }
        }

		
       

        public virtual bool Edit( YZJ_InfoModel model)
        {
            try
            {
                YZJ_Info entity = m_Rep.GetById(model.id);
                if (entity == null)
                {
                    return false;
                }
                              				entity.id = model.id;
				entity.available = model.available;
				entity.StdId = model.StdId;
				entity.StdName = model.StdName;
				entity.StdSex = model.StdSex;
				entity.RepeatNo = model.RepeatNo;
				entity.Entrance_Year = model.Entrance_Year;
				entity.ClassNo = model.ClassNo;
				entity.InResidence = model.InResidence;
				entity.DormitoryBuilding = model.DormitoryBuilding;
				entity.DormitoryNo = model.DormitoryNo;
				entity.AddProvince = model.AddProvince;
				entity.AddCity = model.AddCity;
				entity.AddArea = model.AddArea;
				entity.AddStreet = model.AddStreet;
				entity.AddDetail = model.AddDetail;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    return false;
                }

            }
            catch (Exception ex)
            {                

                return false;
            }
        }

      

        public virtual YZJ_InfoModel GetById(string id)
        {
            if (IsExists(id))
            {
                YZJ_Info entity = m_Rep.GetById(id);
                YZJ_InfoModel model = new YZJ_InfoModel();
                              				model.id = entity.id;
				model.available = entity.available;
				model.StdId = entity.StdId;
				model.StdName = entity.StdName;
				model.StdSex = entity.StdSex;
				model.RepeatNo = entity.RepeatNo;
				model.Entrance_Year = entity.Entrance_Year;
				model.ClassNo = entity.ClassNo;
				model.InResidence = entity.InResidence;
				model.DormitoryBuilding = entity.DormitoryBuilding;
				model.DormitoryNo = entity.DormitoryNo;
				model.AddProvince = entity.AddProvince;
				model.AddCity = entity.AddCity;
				model.AddArea = entity.AddArea;
				model.AddStreet = entity.AddStreet;
				model.AddDetail = entity.AddDetail;
 
                return model;
            }
            else
            {
                return null;
            }
        }

        public virtual bool IsExists(string id)
        {
            return m_Rep.IsExist(id);
        }
		  public void Dispose()
        { 
            
        }

	}
}
