//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using SchoolManager.Models;
using SchoolManager.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using SchoolManager.DAL;
using SchoolManager.BLL;
using Unity.Attributes;

namespace SchoolManager.BLL
{
	public class Virtual_SysExceptionBLL
	{

        public SysExceptionRepository m_Rep =new SysExceptionRepository(new DbContainer());

		public virtual List<SysExceptionModel> GetList( string queryStr)
        {

            IQueryable<tbl_SysException> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
								a=>(a.Id!=null && a.Id.Contains(queryStr))
								|| (a.HelpLink!=null && a.HelpLink.Contains(queryStr))
								|| (a.Message!=null && a.Message.Contains(queryStr))
								|| (a.Source!=null && a.Source.Contains(queryStr))
								|| (a.StackTrace!=null && a.StackTrace.Contains(queryStr))
								|| (a.TargetSite!=null && a.TargetSite.Contains(queryStr))
								|| (a.Data!=null && a.Data.Contains(queryStr))
								
								);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            return CreateModelList(ref queryData);
        }

        public virtual List<SysExceptionModel> CreateModelList(ref IQueryable<tbl_SysException> queryData)
        {

            List<SysExceptionModel> modelList = (from r in queryData
                                              select new SysExceptionModel
                                              {
													Id = r.Id,
													HelpLink = r.HelpLink,
													Message = r.Message,
													Source = r.Source,
													StackTrace = r.StackTrace,
													TargetSite = r.TargetSite,
													Data = r.Data,
													CreateTime = r.CreateTime,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(ref ValidationErrors errors, SysExceptionModel model)
        {
            try
            {
                tbl_SysException entity = m_Rep.GetById(model.Id);
                if (entity != null)
                {
                    errors.Add(Suggestion.PrimaryRepeat);
                    return false;
                }
                entity = new tbl_SysException();
               				entity.Id = model.Id;
				entity.HelpLink = model.HelpLink;
				entity.Message = model.Message;
				entity.Source = model.Source;
				entity.StackTrace = model.StackTrace;
				entity.TargetSite = model.TargetSite;
				entity.Data = model.Data;
				entity.CreateTime = model.CreateTime;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Suggestion.InsertFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHandler.WriteException(ex);
                return false;
            }
        }



         public virtual bool Delete(ref ValidationErrors errors, string id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHandler.WriteException(ex);
                return false;
            }
        }

        public virtual bool Delete(ref ValidationErrors errors, string[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHandler.WriteException(ex);
                return false;
            }
        }

		
       

        public virtual bool Edit(ref ValidationErrors errors, SysExceptionModel model)
        {
            try
            {
                tbl_SysException entity = m_Rep.GetById(model.Id);
                if (entity == null)
                {
                    errors.Add(Suggestion.Disable);
                    return false;
                }
                              				entity.Id = model.Id;
				entity.HelpLink = model.HelpLink;
				entity.Message = model.Message;
				entity.Source = model.Source;
				entity.StackTrace = model.StackTrace;
				entity.TargetSite = model.TargetSite;
				entity.Data = model.Data;
				entity.CreateTime = model.CreateTime;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Suggestion.EditFail);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHandler.WriteException(ex);
                return false;
            }
        }

      

        public virtual SysExceptionModel GetById(string id)
        {
            if (IsExists(id))
            {
                tbl_SysException entity = m_Rep.GetById(id);
                SysExceptionModel model = new SysExceptionModel();
                              				model.Id = entity.Id;
				model.HelpLink = entity.HelpLink;
				model.Message = entity.Message;
				model.Source = entity.Source;
				model.StackTrace = entity.StackTrace;
				model.TargetSite = entity.TargetSite;
				model.Data = entity.Data;
				model.CreateTime = entity.CreateTime;
 
                return model;
            }
            else
            {
                return null;
            }
        }

        public virtual bool IsExists(string id)
        {
            return m_Rep.IsExist(id);
        }
		  public void Dispose()
        { 
            
        }

	}
}
