
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using SchoolManager.Models;
using SchoolManager.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using SchoolManager.DAL;
using SchoolManager.BLL;
using Unity.Attributes;

namespace SchoolManager.BLL
{
	public class Virtual_YZJ_StdGraduationRecordBLL
	{

        public YZJ_StdGraduationRecordRepository m_Rep =new YZJ_StdGraduationRecordRepository(new DbContainer());

		public virtual List<YZJ_StdGraduationRecordModel> GetList( string queryStr)
        {

            IQueryable<YZJ_StdGraduationRecord> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
								
								
								a=>(a.StdId!=null && a.StdId.Contains(queryStr))
								|| (a.StdName!=null && a.StdName.Contains(queryStr))
								|| (a.StdRollId!=null && a.StdRollId.Contains(queryStr))
								|| (a.GraduatedSchoolname!=null && a.GraduatedSchoolname.Contains(queryStr))
								|| (a.GraduatedSchoolNo!=null && a.GraduatedSchoolNo.Contains(queryStr))
								);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            return CreateModelList(ref queryData);
        }

        public virtual List<YZJ_StdGraduationRecordModel> CreateModelList(ref IQueryable<YZJ_StdGraduationRecord> queryData)
        {

            List<YZJ_StdGraduationRecordModel> modelList = (from r in queryData
                                              select new YZJ_StdGraduationRecordModel
                                              {
													id = r.id,
													available = r.available,
													StdId = r.StdId,
													StdName = r.StdName,
													StdRollId = r.StdRollId,
													GraduatedSchoolname = r.GraduatedSchoolname,
													GraduatedSchoolNo = r.GraduatedSchoolNo,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(YZJ_StdGraduationRecordModel model)
        {
            try
            {
                YZJ_StdGraduationRecord entity = m_Rep.GetById(model.id);
                if (entity != null)
                {
                    return false;
                }
                entity = new YZJ_StdGraduationRecord();
               				entity.id = model.id;
				entity.available = model.available;
				entity.StdId = model.StdId;
				entity.StdName = model.StdName;
				entity.StdRollId = model.StdRollId;
				entity.GraduatedSchoolname = model.GraduatedSchoolname;
				entity.GraduatedSchoolNo = model.GraduatedSchoolNo;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {

                return false;
            }
        }



         public virtual bool Delete( string id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {

                return false;
            }
        }

        public virtual bool Delete( string[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {

                return false;
            }
        }

		
       

        public virtual bool Edit( YZJ_StdGraduationRecordModel model)
        {
            try
            {
                YZJ_StdGraduationRecord entity = m_Rep.GetById(model.id);
                if (entity == null)
                {
                    return false;
                }
                              				entity.id = model.id;
				entity.available = model.available;
				entity.StdId = model.StdId;
				entity.StdName = model.StdName;
				entity.StdRollId = model.StdRollId;
				entity.GraduatedSchoolname = model.GraduatedSchoolname;
				entity.GraduatedSchoolNo = model.GraduatedSchoolNo;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    return false;
                }

            }
            catch (Exception ex)
            {                

                return false;
            }
        }

      

        public virtual YZJ_StdGraduationRecordModel GetById(string id)
        {
            if (IsExists(id))
            {
                YZJ_StdGraduationRecord entity = m_Rep.GetById(id);
                YZJ_StdGraduationRecordModel model = new YZJ_StdGraduationRecordModel();
                              				model.id = entity.id;
				model.available = entity.available;
				model.StdId = entity.StdId;
				model.StdName = entity.StdName;
				model.StdRollId = entity.StdRollId;
				model.GraduatedSchoolname = entity.GraduatedSchoolname;
				model.GraduatedSchoolNo = entity.GraduatedSchoolNo;
 
                return model;
            }
            else
            {
                return null;
            }
        }

        public virtual bool IsExists(string id)
        {
            return m_Rep.IsExist(id);
        }
		  public void Dispose()
        { 
            
        }

	}

}
