//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using SchoolManager.Models;
using SchoolManager.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using SchoolManager.DAL;
using SchoolManager.BLL;
using Unity.Attributes;

namespace SchoolManager.BLL
{
	public class Virtual_SysModulePermissionBLL
	{

        public SysModulePermissionRepository m_Rep =new SysModulePermissionRepository(new DbContainer());

		public virtual List<SysModulePermissionModel> GetList( string queryStr)
        {

            IQueryable<tbl_SysModulePermission> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
								a=>(a.Id!=null && a.Id.Contains(queryStr))
								|| (a.ModuleId!=null && a.ModuleId.Contains(queryStr))
								|| (a.PermissionId!=null && a.PermissionId.Contains(queryStr))
								);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            return CreateModelList(ref queryData);
        }

        public virtual List<SysModulePermissionModel> CreateModelList(ref IQueryable<tbl_SysModulePermission> queryData)
        {

            List<SysModulePermissionModel> modelList = (from r in queryData
                                              select new SysModulePermissionModel
                                              {
													Id = r.Id,
													ModuleId = r.ModuleId,
													PermissionId = r.PermissionId,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(SysModulePermissionModel model)
        {
            try
            {
                tbl_SysModulePermission entity = m_Rep.GetById(model.Id);
                if (entity != null)
                {
                    return false;
                }
                entity = new tbl_SysModulePermission();
               				entity.Id = model.Id;
				entity.ModuleId = model.ModuleId;
				entity.PermissionId = model.PermissionId;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {

                return false;
            }
        }



         public virtual bool Delete( string id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {

                return false;
            }
        }

        public virtual bool Delete( string[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {

                return false;
            }
        }

		
       

        public virtual bool Edit( SysModulePermissionModel model)
        {
            try
            {
                tbl_SysModulePermission entity = m_Rep.GetById(model.Id);
                if (entity == null)
                {
                    return false;
                }
                              				entity.Id = model.Id;
				entity.ModuleId = model.ModuleId;
				entity.PermissionId = model.PermissionId;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    return false;
                }

            }
            catch (Exception ex)
            {                

                return false;
            }
        }

      

        public virtual SysModulePermissionModel GetById(string id)
        {
            if (IsExists(id))
            {
                tbl_SysModulePermission entity = m_Rep.GetById(id);
                SysModulePermissionModel model = new SysModulePermissionModel();
                              				model.Id = entity.Id;
				model.ModuleId = entity.ModuleId;
				model.PermissionId = entity.PermissionId;
 
                return model;
            }
            else
            {
                return null;
            }
        }

        public virtual bool IsExists(string id)
        {
            return m_Rep.IsExist(id);
        }
		  public void Dispose()
        { 
            
        }

	}
}
